spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            type:
              mapping: "com.supplychainmanagement.orderservice.event.OrderPlacedEvent:com.supplychainmanagement.notificationservice.event.OrderPlacedEvent"

server:
  port: 8083

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

logging:
  level:
    root: INFO
    com.supplychainmanagement: DEBUG